# Site settings
title: BarCampNola 8: Guardians of the Flame
email: jacqnelson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  BarCampNola 8: Guardians of the Flame
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://barcampnola.com" # the base hostname & protocol for your site
twitter_username: barcampnola
github_username:  spaceotterinspace

# Build settings
markdown: kramdown
