# Site settings
title: Space Otter in Space
email: jacqnelson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site about space otters and tech.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spaceotterinspace.com" # the base hostname & protocol for your site
twitter_username: spaceotterin
github_username:  spaceotterinspace

# Build settings
markdown: kramdown
